set dotenv-required

# run the server
run:
    poetry run uvicorn booklovin.main:booklovin --reload

# run tests
test args='':
    poetry run pytest -v booklovin/tests {{args}}

# run tests and throw gdb on error
debug args='':
    poetry run pytest -v booklovin/tests --pdb {{args}}

# run type checking
checktypes:
    poetry run mypy -p booklovin

# check for dead code using vulture
checkcoverage:
    poetry run vulture booklovin

# check if API contracts are respected
checkprotocols:
    poetry run python ../scripts/validator_db_protocols.py

# generate static docs
docs:
    poetry run pdoc -d google booklovin -o docs

# setup poetry installation
install:
    poetry install
