set dotenv-required

run:
    poetry run uvicorn booklovin.main:booklovin --reload

test args='':
    poetry run pytest booklovin/tests {{args}}

debug args='':
    poetry run pytest booklovin/tests --pdb {{args}}

checktypes:
    poetry run mypy -p booklovin

checkcoverage:
    poetry run vulture booklovin

docs:
    poetry run pdoc -d google booklovin -o docs

install:
    poetry install
