@baseUrl = http://127.0.0.1:8000/api/v1
@testEmail = test@example.com
@testPassword = password
@testUsername = Bidibule


### register

POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "username": "{{testUsername}}",
  "email": "{{testEmail}}",
  "password": "{{testPassword}}"
}

### login

POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username={{testEmail}}&
password={{testPassword}}

### User info

GET {{baseUrl}}/auth/me HTTP/1.1
Authorization: Bearer {{login.response.body.$.access_token}}
